"""Thin OpenAI vision-chat wrapper that always returns validated JSON.

Why a wrapper instead of calling ``openai`` directly:

* The three pipelines all need *strict* JSON output that maps onto a Pydantic
  model. Doing the validation+retry once here keeps each pipeline focused on
  prompt design.
* The wrapper supports ``PIPELINE_USE_STUB=true``. When the env var is on,
  every call returns a deterministic dummy payload generated by the caller.
  That's how the unit tests + the interactive CLI run without hitting the
  network or burning credits.
* The model name is read from settings (``OPENAI_MODEL``) so swapping
  ``gpt-5.4-mini`` for any other vision-capable model is a one-env-var change.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from typing import Callable, Iterable, TypeVar

from pydantic import BaseModel, ValidationError

from app.config import Settings, get_settings

logger = logging.getLogger(__name__)

T = TypeVar("T", bound=BaseModel)

# --- Public dataclasses --------------------------------------------------- #


@dataclass
class VisionImage:
    """One image attached to an LLM call.

    ``data_b64`` holds raw base64 (no ``data:`` prefix) and ``mime_type``
    defaults to ``image/jpeg`` because all our extractors emit JPEGs.
    """

    data_b64: str
    mime_type: str = "image/jpeg"


@dataclass
class LLMRequest:
    """Everything the wrapper needs for a single chat call."""

    system_prompt: str
    user_text: str
    images: list[VisionImage]


# --- Errors --------------------------------------------------------------- #


class LLMConfigError(RuntimeError):
    """Raised when stub mode is off but no API key is configured."""


class LLMResponseError(RuntimeError):
    """Raised when the LLM returns content that cannot be parsed/validated."""


# --- Client --------------------------------------------------------------- #


class OpenAIPipelineClient:
    """Async wrapper around ``openai.AsyncOpenAI`` with retry + stub support."""

    def __init__(self, settings: Settings | None = None) -> None:
        self._settings = settings or get_settings()
        self._async_client = None  # lazy-init so stub mode never imports openai

    def _setting(self, name: str, default):
        return getattr(self._settings, name, default)

    # ---- main entrypoint ------------------------------------------------- #

    async def call_json(
        self,
        request: LLMRequest,
        schema: type[T],
        *,
        stub_factory: Callable[[], T],
        max_retries: int = 1,
    ) -> T:
        """Run one vision chat call and validate the JSON response.

        ``stub_factory`` is invoked when ``PIPELINE_USE_STUB=true`` so the
        caller controls the deterministic fallback (no shared dummy lives in
        this module). ``max_retries`` retries the *whole call* (not the
        validation) when JSON is malformed; on the final failure it raises
        :class:`LLMResponseError` with the raw output for debugging.
        """

        stub_mode = self._setting("pipeline_use_stub", None)
        api_key = self._setting("openai_api_key", None)
        if stub_mode is True or (stub_mode is None and not api_key):
            stub = stub_factory()
            logger.info(
                "pipeline_stub_used model=%s schema=%s",
                self._setting("openai_model", "gpt-5.4-mini"),
                schema.__name__,
            )
            return stub

        if not api_key:
            raise LLMConfigError(
                "OPENAI_API_KEY missing and PIPELINE_USE_STUB is false; "
                "cannot run real LLM call. Set one or the other."
            )

        last_raw: str | None = None
        for attempt in range(max_retries + 1):
            raw = await self._call_once(request)
            last_raw = raw
            try:
                return schema.model_validate_json(raw)
            except (ValidationError, ValueError) as exc:
                logger.warning(
                    "llm_json_invalid attempt=%d schema=%s err=%s",
                    attempt,
                    schema.__name__,
                    exc,
                )
                if attempt == max_retries:
                    raise LLMResponseError(
                        f"LLM returned non-conforming JSON for {schema.__name__}: {exc}"
                    ) from exc
                # Sharpen the system prompt and retry once.
                request = LLMRequest(
                    system_prompt=(
                        request.system_prompt
                        + "\n\nIMPORTANT: Your previous reply was not valid JSON for the "
                        "required schema. Reply with JSON only, no prose, no markdown."
                    ),
                    user_text=request.user_text,
                    images=request.images,
                )

        # Defensive: loop above always returns or raises.
        raise LLMResponseError(f"LLM call failed without producing JSON: {last_raw!r}")

    # ---- internals ------------------------------------------------------- #

    async def _call_once(self, request: LLMRequest) -> str:
        client = self._get_async_client()
        content_parts: list[dict] = [{"type": "text", "text": request.user_text}]
        for image in request.images:
            content_parts.append(
                {
                    "type": "image_url",
                    "image_url": {
                        "url": f"data:{image.mime_type};base64,{image.data_b64}",
                    },
                }
            )

        # Newer OpenAI models (gpt-5.x, o1+, etc.) require ``max_completion_tokens``
        # while older models may still expect ``max_tokens``. We send
        # ``max_completion_tokens`` via ``extra_body`` first so this works even
        # when the installed openai-python stub doesn't expose that keyword.
        common_kwargs = dict(
            model=self._setting("openai_model", "gpt-5.4-mini"),
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": request.system_prompt},
                {"role": "user", "content": content_parts},
            ],
        )
        max_tokens = self._setting("openai_max_tokens", 2000)
        try:
            response = await client.chat.completions.create(
                extra_body={"max_completion_tokens": max_tokens},
                **common_kwargs,
            )
        except TypeError:
            # Defensive fallback for very old SDKs that don't accept extra_body.
            response = await client.chat.completions.create(
                max_tokens=max_tokens,
                **common_kwargs,
            )
        except Exception as exc:
            message = str(exc).lower()
            if "max_completion_tokens" in message:
                response = await client.chat.completions.create(
                    max_tokens=max_tokens,
                    **common_kwargs,
                )
            elif "unsupported parameter" in message and "max_tokens" in message:
                response = await client.chat.completions.create(
                    extra_body={"max_completion_tokens": max_tokens},
                    **common_kwargs,
                )
            else:
                raise

        if not response.choices:
            raise LLMResponseError("OpenAI returned no choices")
        message = response.choices[0].message
        content = message.content
        if not content:
            raise LLMResponseError("OpenAI choice message had no content")
        return content

    def _get_async_client(self):
        if self._async_client is None:
            # Local import keeps stub mode + tests fast: openai's import chain
            # is heavy and we only pay it when we actually need the network.
            from openai import AsyncOpenAI

            # Vision calls with 5+ multi-MB frames routinely take 30-60s on
            # gpt-5-class models. The SDK's default 60s deadline triggers
            # APITimeoutError mid-flight, so we lift it well above that and
            # let the SDK's own ``max_retries`` cover transient blips.
            self._async_client = AsyncOpenAI(
                api_key=self._setting("openai_api_key", None),
                timeout=180.0,
                max_retries=2,
            )
        return self._async_client


# --- Helpers shared by every pipeline ------------------------------------ #


def render_json_block(label: str, payload: dict | list) -> str:
    """Render a JSON block the LLM can read inside a single text part.

    Pipelines pack DINO output, the reference spec, etc. into the user message
    using these blocks. They are formatted with ``label`` + fenced JSON so the
    model can quote labels back in its reasoning if needed.
    """

    return f"{label}:\n```json\n{json.dumps(payload, indent=2, sort_keys=True)}\n```"


def join_text_blocks(blocks: Iterable[str]) -> str:
    """Concatenate text sections with two newlines, ignoring empty entries."""

    return "\n\n".join(b for b in blocks if b)
