import type { Bounty, LeaderboardEntry, User } from "./types";

const now = () => new Date().toISOString();
const inHours = (h: number) => new Date(Date.now() + h * 3600_000).toISOString();
const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

export const DEFAULT_LOCATION = { lat: 34.0689, lng: -118.4452 };

export const MOCK_BOUNTIES: Bounty[] = [
  {
    id: "bnty_001",
    title: "Trash pile near Westwood bus stop",
    description:
      "Bags of household trash dumped behind the bus shelter on the corner. Need someone to bag and dispose at the closest public bin.",
    lat: 34.0635,
    lng: -118.4455,
    address: "1100 Westwood Blvd, Los Angeles, CA",
    reward_sol: 0.18,
    reward_usd_estimate: 28,
    status: "open",
    urgency_score: 86,
    category: "illegal_dumping",
    poster: {
      id: "org_westwoodvc",
      name: "Westwood Village Council",
      avatar_color: "#16a34a",
      is_org: true,
    },
    reference_video_url: null,
    reference_thumbnail_url: null,
    created_at: hoursAgo(3),
    expires_at: inHours(48),
  },
  {
    id: "bnty_002",
    title: "Graffiti on storefront wall",
    description:
      "Newly tagged storefront, paint and rags will be left in a small bin behind the building. Cover with the matching beige paint.",
    lat: 34.0732,
    lng: -118.4413,
    address: "10940 Wilshire Blvd, Los Angeles, CA",
    reward_sol: 0.32,
    reward_usd_estimate: 49,
    status: "open",
    urgency_score: 64,
    category: "graffiti",
    poster: {
      id: "biz_skylight",
      name: "Skylight Boutique",
      avatar_color: "#7c3aed",
      is_org: false,
    },
    reference_video_url: null,
    reference_thumbnail_url: null,
    created_at: hoursAgo(8),
    expires_at: inHours(72),
  },
  {
    id: "bnty_003",
    title: "Beach cleanup — small section, ~30 bags",
    description:
      "Small stretch of Santa Monica beach near the lifeguard tower. Trash bags provided in the shed, key code in the chat.",
    lat: 34.011,
    lng: -118.495,
    address: "Santa Monica State Beach, lifeguard tower 26",
    reward_sol: 0.55,
    reward_usd_estimate: 84,
    status: "open",
    urgency_score: 72,
    category: "beach",
    poster: {
      id: "org_smbc",
      name: "Santa Monica Beach Conservancy",
      avatar_color: "#2563eb",
      is_org: true,
    },
    reference_video_url: null,
    reference_thumbnail_url: null,
    created_at: hoursAgo(11),
    expires_at: inHours(36),
  },
  {
    id: "bnty_004",
    title: "Park bench area covered in food wrappers",
    description: "Need a quick pickup around the picnic tables area, ~10 minutes of work. Bring your own bag.",
    lat: 34.0589,
    lng: -118.4163,
    address: "Westwood Park",
    reward_sol: 0.08,
    reward_usd_estimate: 12,
    status: "open",
    urgency_score: 30,
    category: "park",
    poster: {
      id: "user_alex",
      name: "Alex M.",
      avatar_color: "#f59e0b",
      is_org: false,
    },
    reference_video_url: null,
    reference_thumbnail_url: null,
    created_at: hoursAgo(1),
    expires_at: inHours(24),
  },
  {
    id: "bnty_005",
    title: "Sidewalk litter — plaza side",
    description: "Plaza has ~6 spots of clustered litter, includes broken glass — wear gloves.",
    lat: 34.0712,
    lng: -118.4501,
    address: "Westwood Plaza",
    reward_sol: 0.12,
    reward_usd_estimate: 18,
    status: "claimed",
    urgency_score: 52,
    category: "litter",
    poster: {
      id: "org_uclahousing",
      name: "UCLA Housing",
      avatar_color: "#0a0a0a",
      is_org: true,
    },
    reference_video_url: null,
    reference_thumbnail_url: null,
    created_at: hoursAgo(5),
    expires_at: inHours(30),
    claimed_by: "user_other",
    claim_lock_until: inHours(3),
  },
  {
    id: "bnty_006",
    title: "Recycling bins overflowing on alley",
    description: "Bins are overflowing on Glendon. Consolidate, place inside the gated area.",
    lat: 34.0664,
    lng: -118.4427,
    address: "Glendon Alley",
    reward_sol: 0.22,
    reward_usd_estimate: 34,
    status: "open",
    urgency_score: 58,
    category: "litter",
    poster: {
      id: "biz_glendoncoffee",
      name: "Glendon Coffee",
      avatar_color: "#16a34a",
      is_org: false,
    },
    reference_video_url: null,
    reference_thumbnail_url: null,
    created_at: hoursAgo(2),
    expires_at: inHours(40),
  },
  {
    id: "bnty_007",
    title: "Storm drain blocked by leaves",
    description: "Storm drain on the curb is fully blocked. Just need to scoop and bag, takes 5–10 min.",
    lat: 34.0768,
    lng: -118.4528,
    address: "Selby & Wilshire",
    reward_sol: 0.14,
    reward_usd_estimate: 21,
    status: "open",
    urgency_score: 78,
    category: "other",
    poster: {
      id: "user_priya",
      name: "Priya S.",
      avatar_color: "#e11d48",
      is_org: false,
    },
    reference_video_url: null,
    reference_thumbnail_url: null,
    created_at: hoursAgo(4),
    expires_at: inHours(20),
  },
  {
    id: "bnty_008",
    title: "Abandoned mattress on sidewalk",
    description: "Mattress dumped overnight, blocking the sidewalk. Need someone with a truck OR willing to drag to the curb area.",
    lat: 34.061,
    lng: -118.4365,
    address: "Veteran Ave",
    reward_sol: 0.45,
    reward_usd_estimate: 69,
    status: "open",
    urgency_score: 90,
    category: "illegal_dumping",
    poster: {
      id: "org_la311",
      name: "Neighborhood Watch",
      avatar_color: "#2563eb",
      is_org: true,
    },
    reference_video_url: null,
    reference_thumbnail_url: null,
    created_at: hoursAgo(0.5),
    expires_at: inHours(8),
  },
  {
    id: "bnty_009",
    title: "Park playground — clean wrappers and cans",
    description: "Family-focused area, please be especially thorough near the swings.",
    lat: 34.0552,
    lng: -118.4497,
    address: "Stoner Park",
    reward_sol: 0.16,
    reward_usd_estimate: 24,
    status: "completed",
    urgency_score: 40,
    category: "park",
    poster: {
      id: "user_camille",
      name: "Camille R.",
      avatar_color: "#7c3aed",
      is_org: false,
    },
    reference_video_url: null,
    reference_thumbnail_url: null,
    created_at: hoursAgo(48),
    expires_at: hoursAgo(2),
  },
  {
    id: "bnty_010",
    title: "Trash on the trail entrance",
    description: "Loose trash near the trailhead, pick up and bag.",
    lat: 34.0801,
    lng: -118.4378,
    address: "Bel-Air trail entry",
    reward_sol: 0.1,
    reward_usd_estimate: 15,
    status: "open",
    urgency_score: 36,
    category: "park",
    poster: {
      id: "user_diego",
      name: "Diego L.",
      avatar_color: "#16a34a",
      is_org: false,
    },
    reference_video_url: null,
    reference_thumbnail_url: null,
    created_at: hoursAgo(6),
    expires_at: inHours(60),
  },
  {
    id: "bnty_011",
    title: "Café patio cleanup after event",
    description: "Need help cleaning the patio area after our community event tonight.",
    lat: 34.0648,
    lng: -118.4394,
    address: "Lindbrook Café",
    reward_sol: 0.28,
    reward_usd_estimate: 43,
    status: "open",
    urgency_score: 60,
    category: "other",
    poster: {
      id: "biz_lindbrook",
      name: "Lindbrook Café",
      avatar_color: "#f59e0b",
      is_org: false,
    },
    reference_video_url: null,
    reference_thumbnail_url: null,
    created_at: hoursAgo(0.2),
    expires_at: inHours(12),
  },
  {
    id: "bnty_012",
    title: "Bus stop vandalism — wipe down",
    description: "Marker tags on bus stop bench. Cleaner and rags taped to the back of the post.",
    lat: 34.0691,
    lng: -118.4484,
    address: "Wilshire & Westwood",
    reward_sol: 0.2,
    reward_usd_estimate: 30,
    status: "open",
    urgency_score: 48,
    category: "graffiti",
    poster: {
      id: "org_metro",
      name: "Metro Volunteers",
      avatar_color: "#0a0a0a",
      is_org: true,
    },
    reference_video_url: null,
    reference_thumbnail_url: null,
    created_at: hoursAgo(7),
    expires_at: inHours(48),
  },
];

export const MOCK_USER: User = {
  id: "user_me",
  handle: "you",
  avatar_color: "#16a34a",
  world_id_verified: false,
  joined_at: now(),
  total_earned_sol: 1.42,
  total_completed: 7,
  current_streak: 3,
  wallet: {
    address: "9xQe...K3vM",
    balance_sol: 1.42,
  },
  recent_completed: [
    {
      bounty_id: "bnty_h1",
      title: "Park cleanup — north entrance",
      reward_sol: 0.22,
      completed_at: hoursAgo(28),
    },
    {
      bounty_id: "bnty_h2",
      title: "Beach trash pickup",
      reward_sol: 0.4,
      completed_at: hoursAgo(72),
    },
    {
      bounty_id: "bnty_h3",
      title: "Sidewalk litter run",
      reward_sol: 0.18,
      completed_at: hoursAgo(96),
    },
    {
      bounty_id: "bnty_h4",
      title: "Storm drain unblock",
      reward_sol: 0.12,
      completed_at: hoursAgo(120),
    },
  ],
};

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, user_id: "u_jordan", handle: "jordan_b", avatar_color: "#16a34a", total_earned_sol: 12.4, total_completed: 41 },
  { rank: 2, user_id: "u_marina", handle: "marina.k", avatar_color: "#7c3aed", total_earned_sol: 9.18, total_completed: 33 },
  { rank: 3, user_id: "u_kai", handle: "kai_runs", avatar_color: "#2563eb", total_earned_sol: 8.4, total_completed: 29 },
  { rank: 4, user_id: "u_amaya", handle: "amaya", avatar_color: "#f59e0b", total_earned_sol: 6.7, total_completed: 24 },
  { rank: 5, user_id: "u_sage", handle: "sage_w", avatar_color: "#e11d48", total_earned_sol: 5.95, total_completed: 22 },
  { rank: 6, user_id: "u_devon", handle: "devon", avatar_color: "#0a0a0a", total_earned_sol: 5.2, total_completed: 19 },
  { rank: 7, user_id: "u_lina", handle: "lina_z", avatar_color: "#16a34a", total_earned_sol: 4.4, total_completed: 17 },
  { rank: 8, user_id: "user_me", handle: "you", avatar_color: "#16a34a", total_earned_sol: 1.42, total_completed: 7 },
  { rank: 9, user_id: "u_omar", handle: "omar.m", avatar_color: "#2563eb", total_earned_sol: 1.1, total_completed: 5 },
  { rank: 10, user_id: "u_riley", handle: "riley", avatar_color: "#f59e0b", total_earned_sol: 0.9, total_completed: 4 },
];
